# Generated by Django 4.2.25 on 2025-10-26 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractRegistry', '0005_delete_globaleventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Nombre del Evento')),
                ('event_data', models.JSONField(verbose_name='Datos del Evento (JSON)')),
                ('transaction_hash', models.CharField(max_length=66, unique=True, verbose_name='Hash de Transacción')),
                ('block_number', models.IntegerField(verbose_name='Número de Bloque')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('deployed_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='contractRegistry.deployedcontract', verbose_name='Instancia de Contrato Desplegado')),
            ],
            options={
                'verbose_name': 'Log de Evento Global',
                'verbose_name_plural': 'Logs de Eventos Globales',
                'ordering': ['-block_number', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Nombre del Evento')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deployed_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_subscriptions', to='contractRegistry.deployedcontract', verbose_name='Instancia de Contrato Desplegado')),
            ],
            options={
                'verbose_name': 'Suscripción de Evento',
                'verbose_name_plural': 'Suscripciones de Eventos',
                'unique_together': {('deployed_contract', 'event_name')},
            },
        ),
    ]
