# Generated by Django 4.2.25 on 2025-10-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashPool', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HashPoolEventLog',
        ),
    ]
