# Generated by Django 4.2.25 on 2025-10-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractRegistry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecontract',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional del contrato base.'),
        ),
    ]
