# Generated by Django 4.2.25 on 2025-10-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractRegistry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractversion',
            name='constructor_args_info',
        ),
    ]
