# Generated by Django 4.2.25 on 2025-10-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractRegistry', '0002_remove_contractversion_constructor_args_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedcontract',
            name='params',
            field=models.JSONField(blank=True, help_text='Parámetros del constructor usados en el despliegue.', null=True),
        ),
    ]
