# Generated by Django 4.2.25 on 2025-10-05 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contractRegistry', '0002_basecontract_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
