# Generated by Django 4.2.25 on 2025-10-06 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contractRegistry', '0003_basecontract_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
