# Generated by Django 4.2.25 on 2025-10-26 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractRegistry', '0004_globaleventlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalEventLog',
        ),
    ]
