# Generated by Django 4.2.25 on 2025-10-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractRegistry', '0005_delete_globaleventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='wss_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
