# Generated by Django 4.2.25 on 2025-10-13 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractRegistry', '0003_deployedcontract_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Nombre del Evento')),
                ('event_data', models.JSONField(verbose_name='Datos del Evento (JSON)')),
                ('transaction_hash', models.CharField(max_length=66, unique=True, verbose_name='Hash de Transacción')),
                ('block_number', models.IntegerField(verbose_name='Número de Bloque')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('deployed_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs_tickets', to='contractRegistry.deployedcontract', verbose_name='Contrato Desplegado')),
            ],
            options={
                'verbose_name': 'Log de Evento de Ticket',
                'verbose_name_plural': 'Logs de Eventos de Tickets',
                'ordering': ['-block_number', '-timestamp'],
            },
        ),
    ]
